graspologic-org/graspologic

docs/reference/utils.rst, graspy/utils/utils.py, pytest.ini, tests/test_io.py
Closes #100 
Added function for importing from edgelists. Allows for a single file import or multiple file imports. Since edgelists are sparse, some nodes may get lost if they are completely unconnected. Thus, need to take into account possible differences in nodes in different edgelists by taking the union of all vertices.
=> Import Edgelist function

.travis.yml, tests/test_utils.py
Change travis to run black to see if changes will be needed. Travis build will fail if you are not compliant with Black.
This is to enforce Black formatting.
=> Check for Black Compliance

graspy/embed/base.py, tests/test_base_embed.py
Fixed bug where algorithm choice in ASE, LSE, and Omni was not being passed into `selectSVD` function. 
This is priority PR.
=> [Bug] Fix bug where algorithm choice was not passed

graspy/plot/plot.py, tests/test_plot.py
Closes #179 
Closes #183 
Exposes `vmin` and `vmax` kwargs so that the boundaries of a colormap can be set 
Makes the title of the `heatmap` and `gridplot` appear above the labels when labels are also passed
Allows custom colormaps to be passed to `heatmap`
Could expose a `title_pad` kwarg but I think this works well enough
=> More customization for heatmap, fix titles when using labels

README.md
Add `CONTRIBUTING.md` as a link on the readme. Since we have more and more people contributing, I'm finding that few people have seen the `CONTRIBUTING.md` file.
=> Improve visibility of the contribution guidelines

docs/conf.py, docs/tutorial.rst, graspy/cluster/gclust.py, graspy/cluster/kclust.py, graspy/datasets/base.py, graspy/embed/ase.py, graspy/embed/lse.py, graspy/embed/mase.py, graspy/embed/mds.py, graspy/embed/omni.py, graspy/embed/svd.py, graspy/inference/latent_distribution_test.py, graspy/inference/latent_position_test.py, graspy/models/base.py, graspy/models/er.py, graspy/models/rdpg.py, graspy/models/sbm.py, graspy/pipeline/mug2vec.py, graspy/plot/plot.py, graspy/simulations/simulations.py
Some of #240 
- Document attributes in `Models`
- Explain what pairplot is doing better
- fix `MASE.fit_transform` docs
- Add lots of cross-references 
- Fix many places where `` should have been ````
- Some other changes to documentation, especially spacing
- Some ambiguity with model selection based on whether or not `y` is passed, if it is, should the attribute `vertex_assignments_` just be equal to `y`? (a la mug2vec embedding dimensions) 
- I would love it if the "Read more in the **tutorials**" links actually went to the corresponding .ipynb file but I haven't been able to figure out how to set a label for something that is just in the `tutorial.rst` toctree
=> Improve documentation

graspy/inference/latent_position_test.py, tests/test_latentpositiontest.py
Permutation test p-value should be bounded by 1  / n_bootstraps
=> fix low p bug

graspy/cluster/gclust.py, tests/cluster/test_gclust.py
Closes #203 
[Sklearn's GMM](https://scikit-learn.org/stable/modules/generated/sklearn.mixture.GaussianMixture.html) class allows for a number additional parameters e.g. n_init, max_iter, etc. I've modified graspy's GaussianCluster class to include more of the sklearn parameters: tol, reg_covar,  max_iter, n_init, init_params. I set the default values to be the same as sklearn and I borrowed the documentation from sklearn as well.
=> Add more GMM parameters e.g. n_init (see #203)

graspy/utils/utils.py, tests/test_utils.py
Fixes #261 
Weighted graph functionality for augment_diagonal by adding up nonzero entries and dividing by (nverts-1). Also contains test.
=> Diagonal augmentation for weighted graphs

graspy/embed/ase.py, graspy/models/rdpg.py, graspy/utils/utils.py, tests/test_spectral_embed.py, tests/test_utils.py
Fixes #287 
Fixes #59 
- Updates diag aug to use in and out degree 
- Adds diagonal augmentation as a default for ASE with the option to turn it off
- Seems like we should definitely do augment diagonal for ASE, but what about omni? 
- Should I add a short tutorial about diag-aug (I already wrote the simulation, would just have to write up some text to go with it) 
- Is it worth saving the modified matrix that is actually embedded? Sometimes I like to make screeplots and the like, or just heatmap the matrix itself.
=> Add diag aug as default for ASE, update diag aug behavior for directed

graspy/plot/__init__.py, requirements.txt, setup.py
- added matplotlib >= 3.0 dependency to `requirements.txt` and `setup.py`
- removed backend changing based on system in `plot/__init__.py`
See https://github.com/matplotlib/matplotlib/issues/9017#issuecomment-422400771
matplotlib 3.0.0 fixed the backend fallback behavior, and we were having errors as a result of this block of code in `ndmg` as a result of using either Catalina or a weird python installation, currently unclear which.
I think with `matplotlib>=3.0.0` you guys don't need this.
=> remove matplotlib backend code, add matplotlib dependency to setup.py

graspy/cluster/gclust.py
None
Changes the default `covariance_type` for `GaussianCluster` from "full" to "all"
I find I almost always change to "all" for real data applications so it might as well be the default
=> Update default covariance type for GaussianCluster

.travis.yml, docs/news.rst, docs/release/release_0.2.rst, graspy/__init__.py
=> Release v0.2

.travis.yml, README.md, setup.py
Closes #344 
Removes Python 3.5 as supported language
Updates Travis, setup.py, readme accordingly
A few minor changes to travis.yml just cause of warnings/info from Travis
=> Deprecate Python 3.5

docs/tutorials/inference/latent_distribution_test.ipynb, docs/tutorials/inference/latent_position_test.ipynb, graspy/inference/base.py, graspy/inference/latent_distribution_test.py, graspy/inference/latent_position_test.py, tests/test_latentdistributiontest.py, tests/test_latentpositiontest.py
- Fixes #354
- Fixes #356
- Also see #361
- Transfers the parameter "embedding" from the base class of inference 
- Removes .bootstrap() as the abstract method from the base class, since latent distribution test does not implement it, after the hyppo backend introduction.
- upd: latent position test now uses exact MC p-values
- The attribute representing p-value is now always called .p_value_. 
- .fit() now returns self. added fit_predict() method that fits the model and returns p-value (what .fit() used to be doing previously). Modified the tests and tutorial where necessary accordingly.
- removed .bootstrap() as an abstract method from the base class, since the nonparametric test does not use it. 
- transferred the embedding parameter from the base class to the latent position test, …
=> improved inference api

graspy/inference/latent_distribution_test.py, setup.py, tests/.#test_latentdistributiontest.py, tests/test_latentdistributiontest.py
- Fixes #222 
- Fixes #358  
- Fixes #363 
- Fixes #370  (the 0 permutations part; for change in api see #375)
For #222:
- introduced the sampling from the asymptotic distribution of the ase correction
- added corresponding unit tests
For #358:
- No longer raises an exception with directed inputs
- Added corresponding tests
For #363:
- added the capability to use sklearn kernels (for hsic test, which is same as mmd) 
- raising warnings when distance used with hsic or kernel used with hsic
- added corresponding unit tests
For #370:
- No longer raises an exception with 0 bootstraps
- fit_predict left unchanged (returns a nan if used with 0 bootstraps)
Miscellaneous:
- removed gaussian medial kernel implementation and instead importing it from hyppo
- avoid code duplication 
- that version …
=> Latent distribution test size

docs/tutorials/inference/latent_distribution_test.ipynb, requirements.txt
seaborn https://github.com/mwaskom/seaborn/issues/2194 
- Fix bug in master due to new matplotlib 3.1.1 
- Reduce number of bootstraps in `LatentDistributionTest` tutorial to make it run faster
=> Set maximum MPL version, reduce LDT tutorial runtime

graspy/cluster/base.py
Fixes #369 
Removes ari return value from `fit_predict` and `predict` functions in base for cluster class
=> Remove ari return value from AutoGMM.fit_predict

requirements.txt, setup.py
Consolidated our requirements into a single file, setup.py.  Also updated it to include a new extra requires target that includes all of our build tools; black, pytest, pytest-cov, mypy, and sphinx-rtd-theme.
We can continue using `pip install -r requirements.txt` for all development purposes.  Downstream consumers (installing via pip, for instance) will only install the minimum runtime requirements.
This also reduces the total LOC by de-constantizing the strings that are used in only one place.  I also bumped the "lower than 3.6 and we have to exit" check to the very top.  No use in doing work if we're just going to exit out anyway.
Closes #466
=> Consolidated our dependencies

docs/reference/subgraph.rst
Fixes a documentation build warning that occurred with PR #322. 
This PR extends the title underline to match the length of the text, and thereby resolves the documentation build warning
=> Fix the title

.github/workflows/build.yml
The last test of the `build-devops` branch and associated PR ended up not working on merge to dev.  Trying something else now :\
=> Sounds like the refs name will be a full path

.github/workflows/build.yml
I'm not sure which part of the `if` expression is failing, or if it's something else.  I removed the "merged from PR" since I'm not even convinced we want that and this will let me isolate if the problem is in the `github.ref` checks or something else.
=> Publish on push to dev/main, take 2

.github/workflows/build.yml
In theory, simply adding pull_request to the list of triggers is all we need to run the build workflow on a forked repository.
Documentation: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories (scroll up a bit to read all of the PR content, but the "from forks" is the part we were failing at before)
I think this will work.  Of course, I thought `pull_request_target` would work too.
=> Run build on PR

graspologic/match/gmp.py
Closes #513 
Remove the distinction from fit and fit_predict that A and B must be positive adjacency matrices
=> Update docs to show GM can accept negative entries in A, B

setup.py
Updated joblib version to fix parallelization issue that is Windows-specific.  Closes #582
=> Updating joblib version to fix #582

docs/tutorials/embedding/OutOfSampleEmbed.ipynb
I keep noticing a few small things from OOS that I want to fix up.
Small PR to make the OOS tutorial have better comments.
=> better comments in OOS tutorial

README.md
`None`
Just changes the source of the downloads shield to https://pepy.tech/project/graspologic
I like that this has a cumulative count as opposed to how many per week/month.
=> Change downloads count in Readme to cumulative from pepy

tests/test_mug2vec.py, tests/test_sklearn.py
Fixes #618 
- Fixes bug from `check_estimator` inputs changing
- Fixes bug from a `mug2vec` test failing - I am not sure what changed in `GaussianMixture` to cause this. Changing the random seed also appeared to fix this bug on my machine, but I figured that making the problem slightly easier would be more robust.
We probably don't even need these `check_estimator` tests, at some point we wanted to verify sklearn-ness explicitly, not sure that we care now. Note that ASE was taken off this list because of the out of sample stuff.
=> Bug fixes for sklearn 0.24 compatibility

CONTRIBUTING.md, ROLES.md
Part of #531 
Adds the Roles and Responsibilities page to the actual repo as opposed to just the wiki.
I think the wiki was not visible enough. Not sure where else in the package we should be directing people to this new page but I figured having it would be better than nothing. 
Really trying to wrap up #531 so let me know if anyone has any concerns. I know many people are out for break right now so no worries if this waits until people are back! Happy holidays.
=> Add "Roles" to top of repo

graspologic/__init__.py
Without importing it, it doesn't show up as a package for use.
=> Forgot to actually import `graspologic.layouts`

graspologic/datasets/base.py
Currently, there's no data given to the user relating a mouse's subject ID to its genotype. This is not needed for most group-level analyses (omnibus embedding, clustering, etc.), but necessary if you want to analyze the anatomical data ([link](https://github.com/microsoft/graspologic/tree/dev/graspologic/datasets/mice/features)).
I've made a one-line change that gives the user access to `participants.csv`, a dataframe with genotype and subject id information.
=> Include participants in mouse data given to users

.gitignore, docs/Makefile
JHU had had some commands in the neurodata netlify build process for graspy/graspologic that didn't work anymore with our new split documentation setup.  @bdpedigo and I did a quick update of the build commands to use and I created a Makefile to call instead of having a bunch of separate commands shoved into their account.
In the long run we hope to retire netlify in favor of RTD but something is wrong with the RTD oauth and Github and I haven't had the time to dig into it yet.
=> Preparing a Makefile so that netlify can use it

setup.cfg
Fixes #659 
Pins hyppo version to `0.1.3` to fix the bug when importing `hyppo._utils` caused by its new release.
=> Fix hyppo version to avoid import error

README.md
Update broken link to tutorial section where the documentation is now accessible.
It just fixes the broken link in the README file.
=> Update broken link to the tutorial section

docs/reference/release.rst, docs/reference/release/graspy_releases.rst, docs/reference/release/release_0.3.rst
Let's release 0.1.0.
I had grandiose plans to try to get every PR listed and every contributor within the release range and... it's just weird because we're effectively a new project that morphed from two old ones and I don't even know how to go about showing changelogs between them both.  
So we'll start fresh with 0.1.0 and have proper changelogs after that!
@bdpedigo in particular we will want to make sure any new changes after 0.1.0 will be put into the release notes/changelog  going forward.  We don't want to try to wrap these all up later, so we'll have each person submitting a PR add to the changelog as we go with something short but descriptive as we pull in PRs.
=> 0.1.0 release notes

.github/PULL_REQUEST_TEMPLATE.md
Since versioning is now an important part of our PR process that we hadn't really had to worry about before, I wanted to make some additions to the PR template to (hopefully?) help speed up the resolution of any of those concerns by adding a checklist up front.
@saadhaxxan had a PR with a more robust checklist that we ended up not using at the time, but many of the items in that checklist would make sense to add in here. In the PR we closed (#493) we noted we'd need to add a checklist at some point, and we still haven't. 
In the short term I propose we take this small change, but we create an issue and agree on a set of items to have in the checklist.  I'd like to agree on the changes to this PR template in the short term, just so we have some operating procedures codified and can get …
=> Adding a small checklist to the PR template

graspologic/match/gmp.py
None
Fixes a bug in the GraphMatch docstring about initializations from the barycenter
@asaadeldin11 this is no longer true at all, right?
=> Fix bug in GraphMatch docs

graspologic/align/seedless_procrustes.py
None
Fixes a bug (I think?) where the wrong parameter was used in sinkhorn. 
I haven't tested the effects of this much - but seems like they could be huge if eps is less than one. My guess is SeedlessProcrustes would always terminate after one iteration or something like that with the old code
cc @tliu68 who found this issue
cc @alyakin314 who may have thoughts
=> Fix incorrect use of optimal transport params in Seedless Procrustes

README.md
None
Removes the warning from the readme about the merger
I think we are safely at the point where there aren't any unresolved *merger-specific* issues like missing references to graspy or topologic that we have yet to notice. so i vote we remove this warning. 
We do still have a note about "History" [here](https://graspologic.readthedocs.io/en/latest/#history)
=> remove merger warning from readme

graspologic/inference/latent_position_test.py, tests/test_latentpositiontest.py
- Added parallelized computation of bootstrap null
None
=> Parallelize bootstrap for latent position test

graspologic/match/gmp.py, graspologic/match/qap.py, tests/test_match.py
QAP incorrectly assumes the partial_match is sorted when partial_match.shape[0] == A.shape[0]. Fix this.
=> Fix outlier handling in qap when len(seeds)==n

mypi.ini, mypy.ini
While we slowly plug away at the `type-hint` branch, I wanted to get this updated mypy.ini config pushed first so that we could at least have some more actionable "type hinting is broken" error messages in our build-failed stuff.  @bdpedigo and @loftusa have been clamoring for this for aaaaaages so I finally buckled down and did it.
In this PR no code changes were done, but the [proper canonical config file](https://mypy.readthedocs.io/en/stable/config_file.html) was added instead of the old weird typo version, and we should now have a bunch of "oh man that's a lot of work" errors to sort through.
=> Enable better type hint errors

graspologic/layouts/__main__.py
If there is no weight a weight of 1.0 will be added for each edge that
is missing a weight. A warning message will be logged that there are no
weights. If all all edges have the same weight there may be an issue
if the number of edges is greater than max_edges and we try to trim
edges.
- [N ] Does this PR add any new dependencies?
- [N ] Does this PR modify any existing APIs?
=> For auto layouts - Allowing files with only (source, target)

graspologic/layouts/nooverlap/_quad_node.py
During the contraction phase of the no-overlap portion of the layout there is a case where we could have a divide by 0 error.
This change adjusts the new node position by a small amount.
=> Fixing a rare, division by 0 case

graspologic/embed/mase.py
None
- Fixes a bug where if `n_components` was specified and > `int(np.ceil(np.log2(np.min(self.n_vertices_))))` then the initial embeddings were too small for what the user wanted
- removed unused imports
Also avoids computing too many dimensions if not using automatic dimensionality selection
=> Fix bug in MASE initial `n_components`

docs/reference/reference/index.rst
This PR fixes the cluster tab redundancy in the graspologic reference: https://graspologic.readthedocs.io/en/latest/reference/index.html
=> Deleted the cluster redundancy in reference

graspologic/partition/leiden.py, setup.cfg, tests/partition/test_leiden.py
Added trials parameter to leiden and set a new requirement of graspologic-native 1.0.0 or higher to use it.
=> Added trials parameter to leiden

graspologic/plot/plot_matrix.py, tests/test_plot_matrix.py
None
- Allows the user to pass sparse matrices to `adjplot` and `matrixplot` when using the `scattermap` option
- Could absolutely have a conversation about the best API for these functions. I'm not currently that happy with it, but don't want to let that hold up this PR.
=> Add sparse matrix support for some matrix plotting functions

graspologic/utils/utils.py, tests/test_utils.py
Fixes #791 
We also discussed in #655 
- Adds support for scipy sparse adjacency matrices in `largest_connected_component`
- Uses this function for numpy ndarray inputs as well
- We could also fix up `multigraph_lcc_intersection` and `multigraph_lcc_union`. Someone is welcome to open a separate issue and add that if so desired, it would be good to have for consistency's sake too. 
cc: @dlee0156
=> Add a scipy sparse largest connected component finder

graspologic/utils/utils.py, tests/test_utils.py
Fixes a bug where explicit 0s stored in a scipy sparse matrix were treated as edges for the purposes of the largest connected component calculation. This was potentially causing inconsistent behavior depending on whether the array was represented as sparse or dense.
=> [BUG] Fix bug with 0s in sparse matrix for LCC calculation

CONTRIBUTING.md, graspologic/pipeline/embed/adjacency_spectral_embedding.py, graspologic/pipeline/embed/embeddings.py, graspologic/pipeline/graph_builder.py, setup.cfg, tests/pipeline/embed/test_adjacency_spectral_embedding.py
- [Y ] Does this PR add any new dependencies?
- [Y] Does this PR modify any existing APIs?
- [Y ] Is the change to the API backwards compatible?
- [N/A] Have you built the documentation (reference and/or tutorial) and verified the generated documentation is appropriate?
none
This PR adds beartype runtime type checking to the "pipeline" package.  Beartype checks input values against PEP-compliant type hints.  When the type is nested (such as arrays or arrays of arrays) beartype samples data to maintain runtime speed.
=> Automated type checking with Beartype

docs/reference/reference/pipeline.rst, graspologic/pipeline/embed/omnibus_embedding.py
=> Add omnibus_embedding_pairwise to pipeline.rst

graspologic/utils/utils.py, tests/test_utils.py
1. Replace filtering Python loop that checks each nonzero entry with library methods that compare counts of nonzeros after applying a broadcast filter operation
2. Add unit tests to expand coverage for ndarray and csr_matrix inputs to utils.is_unweighted
=> improve utils.is_unweighted for sparse graphs

graspologic/embed/lse.py, graspologic/embed/n2v.py, graspologic/pipeline/embed/laplacian_spectral_embedding.py, tests/embed/test_n2v.py, tests/layouts/test_auto.py
Jon Larson thinks our node2vec defaults are way out of wack given normal settings used in production.
We're adjusting to be more in line with those.
Also added documentation to LSE that more directly links to the to_laplacian function that actually
shows the forms being used and their mathematical notation.
=> Documentation and default parameter updates

setup.cfg
Closes #726 
Updates the version spec to allow most recent versions of matplotlib
I am still not sure EXACTLY which versions in 3.3.* raised an issue with one of our tests in `tests/test_plot.py`. Because of this, I am just changing the specification to not allow ANY version in 3.3.*, even though I think we could get more specific about what is actually broken. If anyone wants to investigate which versions are actually broken feel free. But for now, I think this is an improvement. 
I have tested 3.4.0 - 3.4.3 on my machine locally and tests passed.
=> Update `matplotlib` version specification to only disallow `3.3.*`

docs/conf.py, docs/reference/reference/partition.rst, graspologic/partition/__init__.py, graspologic/partition/leiden.py, mypy.ini, setup.cfg, tests/partition/test_leiden.py
Fixes #901
This PR kind of needs a bit of a history lesson.  Back in the day, when we first added this, all node ids had to be strings.
They had to be strings because it seemed easier to turn an int into a string than a string into an int (this is not necessarily true, but that *was* the thinking at the time).  And because we had to turn it into a string *somewhere*, we did it in Python, because nobody wants to try to make Rust carefully coerce Anything At All into Strings.  No one. 
So Rust expected a String id, and our python wrapper just said "hey, you guys know how to make other things into strings, you do it".  And then users said "but we don't want to, and why are integers so scary to you anyway", and we said "ok, that is fair I guess" and so we tried to get clever by converting all …
=> Fixed bug / suboptimality with leiden/hierarchical_leiden starting_communities

.github/workflows/build.yml, README.md, docs/conf.py, docs/reference/reference/cluster.rst, docs/reference/release.rst, graspologic/embed/ase.py, graspologic/embed/base.py, graspologic/inference/latent_distribution_test.py, graspologic/inference/latent_position_test.py, graspologic/partition/leiden.py, graspologic/pipeline/embed/adjacency_spectral_embedding.py, graspologic/pipeline/embed/embeddings.py, graspologic/pipeline/embed/laplacian_spectral_embedding.py, graspologic/pipeline/embed/omnibus_embedding.py, pyproject.toml, setup.cfg, tests/partition/test_leiden.py, tests/pipeline/embed/test_adjacency_spectral_embedding.py, tests/pipeline/embed/test_embeddings.py, tests/pipeline/embed/test_laplacian_spectral_embedding.py, tests/pipeline/embed/test_omnibus_embedding.py, tests/test_plot.py
~~Hyppo 0.2.2 (and possibly earlier) use a private scipy function that has been moved in 1.8.0+. Until hyppo fixes this we need to restrict scipy to an earlier version.~~
~~This should be removed once hyppo releases a fix.~~
This branch and PR are just morphing into a general purpose cleanup prior to releasing 1.0.0 (for real this time) and fixing our dependencies.
=> 1.0.0 prep and dependency adjustments

graspologic/partition/leiden.py
The exception we raise when given a networkx graph if it's directed or a multigraph implies the only error condition is that it's a directed graph, when that isn't the case.
=> Error message in Leiden when given a multigraph was incorrect

graspologic/models/edge_swaps.py
Fixes #964
this code fixes the issue of repeated compilations of numba in the if/else statement of edge_swaps.py and, instead, sets the jit to a variable at the bottom of the file in order for the jit to compile only once. this makes the code run faster
=> Fixed repeated numba compilation in EdgeSwapper (#964)

graspologic/plot/plot.py
I thought it would be nice to have an option that plots a marker with an estimated elbow at the screeplot.
This simple PR adds it.
=> Added elbow marker to screeplot in plot module

setup.cfg
Closes #995 
This should allow Seaborn and Matlab plot to co-exist in graspologic
=> Fixed bug where seaborn was incompatible with matplotlib 3.6.1

README.md
Removed outdated Zenodo DOI from README.md
**BEFORE**
**AFTER**
=> [BUG FIXED] Removed outdated Zenodo DOI from README.md

docs/tutorials/embedding/CovariateAssistedEmbed.ipynb, graspologic/match/solver.py, setup.cfg, tests/test_match.py
Fixes #1001.
- I add padding to the similarity matrix S, so the following `_compare_dimensions` checks are passing.
- Also fixes a small error with auto doc generation from an upstream dependency.
=> Fixed graph matching with similarity matrix of unequal dimensions

CONTRIBUTING.md
My edits were based on my experience with getting set up on GitHub. I added some minor changes of things I wish I had read while I was trying to set up my account.
=> Edited contributing guidelines

setup.cfg
seems so
nope
nope
irrelevant
unapplicable?
Fixes #1015.
Quick-patches the incompatibility by avoiding the netoworkx v.3.0. 
Probably need a better long term fix. Unsure if removing the orderedgraph arguments is sufficient and/or backward compatible.
=> hard capped networkx version to avoid incompatability

docs/tutorials/models/edge_swaps.ipynb, graspologic/embed/ase.py, graspologic/embed/lse.py, graspologic/embed/mase.py, graspologic/embed/omni.py, graspologic/embed/svd.py, graspologic/match/solver.py, graspologic/match/types.py, graspologic/match/wrappers.py, graspologic/models/edge_swaps.py, graspologic/partition/leiden.py, graspologic/pipeline/embed/_types.py, graspologic/pipeline/embed/adjacency_spectral_embedding.py, graspologic/pipeline/embed/laplacian_spectral_embedding.py, graspologic/pipeline/embed/omnibus_embedding.py, graspologic/plot/plot.py, graspologic/plot/plot_matrix.py, graspologic/types.py, graspologic/utils/utils.py, setup.cfg, tests/embed/test_omni.py, tests/partition/test_leiden.py, tests/pipeline/test_graph_builder.py, tests/test_latentdistributiontest.py, tests/test_models.py, tests/test_plot.py, tests/test_plot_matrix.py, tests/test_spectral_embed.py, tests/test_utils.py
- no
Fixes #961
Proper fix of #1015 
- Technically, we're losing support for `nx.OrderedGraph`, but I'm not losing and sleep over that one. I was even considering just switching to NetworkX 3 support only but I don't think it's fully necessary.
=> Fixed NetworkX 3 compatibility and switched to sparse arrays (not matrices)

graspologic/embed/svd.py, graspologic/utils/utils.py, tests/partition/test_leiden.py, tests/test_spectral_embed.py
=> Fixed bugs in type specifications from Numpy 1.25 release

docs/reference/release.rst, graspologic/match/solver.py, graspologic/match/wrappers.py
N/A
Changed internal `match/solver.py` code to:
- avoid repeated matrix multiplications
- compute `trace(X @ Y)` more efficiently
The modified implementation definitely avoids unnecessary computation.  Benchmarking this algorithm is hard (very data dependent) so YMMV, but these changes give a 1.5-2x speedup for the settings that I tested.
- No additional dependencies
- No API changes
- Have not build the documentation - only modified internal functions that are not documented
=> Added option for more efficient graph matching matrix operations

graspologic/plot/plot.py
- [ x] Does this PR have a descriptive title that could go in our release notes?
- [x ] Does this PR modify any existing APIs?
- [ x] Is the change to the API backwards compatible?
- [x ] Have you built the documentation (reference and/or tutorial) and verified the generated documentation is appropriate?
Fixes #840 
As requested, an argument was added to `screeplot()` for passing in custom axes. If an `ax` argument is not specified, it defaults to `plt.gca()` to prevent issues with code that does not supply an argument.
N/A
=> Added an `ax` argument for `screeplot()` (FIxes #840)

graspologic/layouts/render.py, graspologic/plot/plot.py, graspologic/plot/plot_matrix.py
=> Fixed Matplotlib 3.8 compatibility issues

.github/workflows/build.yml, .github/workflows/publish.yml
This CI update moves matrix-strategy dimensions with a single value into env variables. This simplifies the output task names, and will let us update Poetry versions without interfering with branch protection strategies.
=> Move single-length matrix strategy dimensions to env-vars
