graspologic-org/graspologic

graspy/utils/utils.py, tests/test_utils.py
Per jovo request, this is what I saw used in the two truth's paper
=> Add DAD laplacian normalization

graspy/embed/mds.py, graspy/embed/omni.py, tests/test_mds.py
Closes #48 
Refactor the computing of dissimilarity to ClassicalMDS from omni. Looking for feedback for explanation for n_elements if it makes any sense. Generalized it so that it can compute row-wise distance or block-wise distance.
=> refactor dissimilarity function from omni to mds

graspy/embed/svd.py, tests/test_select_dimension.py
Better edge case handling when you have 2 singular values or small matrix
=> Selectdim fix

graspy/plot/plot.py, graspy/utils/utils.py, tests/test_utils.py
- Fixes gridplot axis reversal bug, and makes sure gridplot preserves spacing of empty blocks of nodes 
- Adds ability to modify scalar weight of diag aug 
- Makes multigraph lcc recurse when necessary
- Makes sure lcc isn't modifying input graph
=> Misc bug fixes and additions

.gitignore, graspy/plot/plot.py, notebooks/bpedigo/new_pairs.py
adds ability to specify marker size and type, also turns off the default white borders around seaborn marker plots
=> Pairplot tweaks

graspy/embed/lse.py, graspy/utils/utils.py, tests/test_utils.py
implements regularized laplacian embedding
=> added regularized laplacian

graspy/utils/ptr.py
#131 
Change the default pass to ranks method to `simple-nonzero`.
=> Change default for PTR

docs/conf.py, docs/index.rst, docs/reference/utils.rst, graspy/__init__.py, graspy/utils/utils.py, setup.py
Closes #147 
- will fix PyPI README render for next version.
=> Fix versioning in docs and add useful links section, misc changes

graspy/cluster/base.py, graspy/cluster/gclust.py, graspy/cluster/kclust.py, graspy/embed/ase.py, graspy/embed/base.py, graspy/embed/lse.py, graspy/embed/mds.py, graspy/embed/omni.py, graspy/embed/svd.py, graspy/inference/base.py, graspy/inference/nonpar.py, graspy/inference/semipar.py, graspy/plot/plot.py, graspy/simulations/simulations.py, graspy/utils/ptr.py, graspy/utils/utils.py
Closes #163 
The core devs have decided to remove author info from headers and only include licenses in source files.
=> Remove author headers, add license

docs/release/release_0.0.3.rst
=> release 0.0.3

graspy/cluster/gclust.py, tests/cluster/test_gclust.py
Fixes and closes #201 
- Fix `n_component_` calculation
- Add `covariance_type_` attribute to denote the best covariance type
- Change tests to check `n_components` rather than calculating this in the tests using `bic_`
=> Gclust fix

CONTRIBUTING.md
Update the `CONTRIBUTING` so that people know how to test locally.
=> Add bullet for testing

MANIFEST.in, setup.py
=> Fix dataset loading and exclude tests folder

docs/reference/plotting.rst, graspy/inference/latent_position_test.py, graspy/plot/plot.py, graspy/simulations/simulations.py, graspy/utils/utils.py
Closes #224 
Closes #223 
Closes #214 
Closes #210
- Adds a `log10` option as one of the possible graph transformations for plotting
- Fixes the behavior of block-separating lines for small graphs 
- Adds a kwarg `sort_nodes` to specify whether or not to sort nodes by degree for `heatmap` and `gridplot`, default is `False` (this is up for debate, but this has confused multiple people). 
- Changes the default for `symmetrize` to `avg`
- Adds documentation for other plotting functions to the web docs
=> Minor plotting fixes and additions, change symmetrize default

README.md
Add `pandas` to README as dependency
=> Update README to add pandas as dependency

graspy/inference/latent_distribution_test.py, tests/test_latentdistributiontest.py
Fixes #218 
Allows input of directed data to fit function
=> Allow directed input for LatentDistributionTest

docs/news.rst, docs/release/release_0.1.rst, graspy/__init__.py
Changelogs and doc update for v0.1
=> v0.1 Release 

docs/tutorials/models/models.ipynb
Add citation to models tutorial
=> add citation to models tutorial

graspy/models/base.py, tests/test_models.py
Fixes #216 
Check that input graph is same size as P matrix when using score in the model selection code.
=> Fix input protection for score method

graspy/cluster/pyclust.py, tests/cluster/test_pyclust.py
PR Pyclust.
Add label_init, max_iter, verbose to pyclust and corresponding test function.
=> Pyclust, add new functionality

graspy/embed/svd.py
None
Adds small modifications to enable compliance with new sklearn 0.22 `check_estimator`
=> Fixes for sklearn 0.22 compliance

README.md
Closes #129 
Adds links to GraSPy paper
=> Update readme with paper info

graspy/embed/ase.py, graspy/embed/omni.py, graspy/embed/svd.py, graspy/inference/latent_distribution_test.py, graspy/inference/latent_position_test.py
Fixes #181 by removing unnecessary references.
=> removed references

graspy/cluster/autogmm.py, tests/cluster/test_autogmm.py
Uses joblib to parallelize the different initializations for AutoGMM
Need to change verbose argument to be more consistent with sklearn
=> Parallelize AutoGMM

graspy/plot/plot.py
Fixes #239 
Let heatmap accept arbitrary arguments
Merged from self branch to avoid the test failure caused by the previous commits
=> Let heatmap accept arbitrary arguments

docs/conf.py, docs/requirements.txt, graspy/cluster/autogmm.py, graspy/cluster/base.py, graspy/cluster/gclust.py, graspy/cluster/kclust.py, graspy/embed/ase.py, graspy/embed/base.py, graspy/embed/lse.py, graspy/embed/mase.py, graspy/embed/mds.py, graspy/embed/omni.py, graspy/embed/svd.py, graspy/match/faq.py, graspy/plot/plot.py, graspy/utils/ptr.py, graspy/utils/utils.py
Made the graspy doc website great again.
=> Changes to doc website

tests/cluster/test_autogmm.py
Fixes #325 
Removed repeated testing for various settings. I think its fine to ignore the repeated testing for AutoGMM.
AutoGMM tests run in about 2 minutes.
=> Remove repeated testing in AutoGMM

graspy/simulations/simulations.py
None
`rescale` option in RDPG is probably dumb almost always. Definitely shouldn't be the default
Also changed `loops` to False by default since most other sims we have do that
=> Update defaults for RDPG sim

graspy/embed/mase.py
Fix #340 
Changed default to `scaled=True`.
=> Update scaled default

.travis.yml, README.md, graspy/embed/mase.py, graspy/simulations/simulations.py, setup.py
Removing 3.5 support to pass tests that fail due to hyppo
=> Removing 3.5 support to pass tests that fail due to hyppo

graspy/match/gmp.py
Fixes #386. One-liner as far as I can tell.
=> GraphMatch inherits from BaseEstimator

README.md
Just thought we should have something temporarily as people may be seeing the repo for the first time and be confused by stuff, e.g. the name mismatch. Though I expect we'll have this all sorted out soon, I thought this couldn't hurt.
=> Brief warning about the merger in README for the time being

docs/conf.py
Fixes `build_documentation` errors that somehow popped up on all open PRs.
Also fixed some warnings from intersphinx while I was at it related to `.inv` files of other libraries moving.
I do not question the will of the intersphinx gods
=> Intersphinx woes

.github/CODEOWNERS
just commented out for now, felt like it was still okay to have that information live where it does but not actually do anything on github. if you disagree, feel free to remove that file and put the info somewhere else?
=> Turn off codeowners

README.md
Fixes #540
Optimize badges for FIRM guidelines
=> Add pypi version badge and update codecov badge

CONTRIBUTING.md
None
Fix code block & typos in `CONTRIBUTING.md`
"Please ensure all code snippets and error messages are formatted in appropriate code blocks." XD
@bdpedigo
=> Fix code block & typos in the contribution guidelines

docs/tutorials/embedding/OutOfSampleEmbed.ipynb
Small addition to the recently-merged oos PR -- I realized the heatmaps didn't have titles.
=> add titles to heatmaps

README.md
Related to #508 
Still need to set up PR preview so not going to close that issue. 
Changes documentation links to the new Read the Docs location
=> Update documentation location to RTD

README.md
Close #625 
Removed the dependencies section from the README.md file
=> Updated the README.md by removing the Dependencies 

graspologic/partition/modularity.py
The document string reports the wrong return type.
=> fixing incorrect document string

graspologic/partition/modularity.py
I did a god merge without realizing it.  :(
=> Fix for `Fix modularity docstring`

graspologic/plot/plot.py, tests/test_plot.py
PR#541
Adds code to format `gmm.covariances_` in `pairplot_with_gmm` to enable plotting of ellipses for GM models with all covariance types.
=> reformat gmm.covariances_ in pairplot_with_gmm

graspologic/__init__.py
=> include nominate

graspologic/align/seedless_procrustes.py
=> Added Reference for Seedless Procrustes

docs/reference/in-the-wild.rst, docs/reference/index.rst
Closes #741 
Adds a section to the main sidebar of the docs called "graspologic in the wild" which includes examples of stuff people have done with the package.
- We'll obviously need to keep updating this list periodically, would be great if people PR things in when they do them!
- Happy to take any additions now too, please just PR into this branch if you have anything.
=> Add "graspologic in the wild" page

docs/reference/cli.rst, graspologic/layouts/__main__.py, graspologic/layouts/auto.py
Now you can skip running the very slow, tedious no-overlap part of auto layout!
=> Optional layout steps

graspologic/embed/mase.py
None
Fixes a bug in how the MASE score matrices were calculated
=> Fix bug in MASE score calculation for directed

docs/reference/release.rst
=> Release notes for 0.2.0

graspologic/utils/utils.py
`is_unweighted` doesn't work properly for a sparse array input
I think we could instead just do `graph[graph != 0].max() == 1 and graph[graph != 0].min() == 1`
for that entire section of the code.
=> Fix bug in `is_unweighted` for sparse

CONTRIBUTING.md
Added a documentation section describing developer initialization steps.
=> Added developer initialization documentation

.github/workflows/build.yml
Publish documentation to /latest as well as the versioned folder on main branch build
=> Publish to /latest on main deployment

README.md
Just updates hyperlinks to docs in a few places
Currently I believe the "latest" version of the docs is not working. I think this is the one we should point people to, but lets not merge this until "latest" is online
=> Updated documentation link references

graspologic/layouts/auto.py, tests/layouts/test_auto.py
Fixes #893 
The value we're finding is a float, which we then were (foolishly) using to subscript into an array.
Absolutely my mistake.
=> Fixed a bug in automatic layouts if we prune low weight edges

tests/embed/test_n2v.py
Fixes #880 
Add a random seed to n2v test to fix intermittent failures.
=> Add random seed specification to n2v test

.github/workflows/build.yml, graspologic/align/seedless_procrustes.py, graspologic/cluster/autogmm.py, graspologic/embed/base.py, graspologic/embed/case.py, graspologic/embed/mds.py, graspologic/embed/n2v.py, graspologic/inference/latent_position_test.py, graspologic/layouts/nooverlap/_quad_node.py, graspologic/match/qap.py, graspologic/models/sbm_estimators.py, graspologic/pipeline/embed/adjacency_spectral_embedding.py, graspologic/pipeline/embed/laplacian_spectral_embedding.py, graspologic/pipeline/embed/omnibus_embedding.py, graspologic/simulations/simulations.py, setup.cfg, tests/test_models.py, tests/test_select_dimension.py
- Closes #910
- Solution here was updating to use Gensim>4.0.0 which is more modern/supported
- Closes #909
- Updates many files because of changes to how `black` handles power operators
- Switches actions to use `setup-python@v2` because of a bug with v1, and also cause why not
=> Fixed gensim, mypy, setup-python, and black issues

docs/reference/in-the-wild.rst
=> Added entries to in-the-wild.rst

graspologic/simulations/simulations.py
=> Fixed a typo in an error message

docs/reference/release.rst
=> [WIP] Added release notes

graspologic/models/er.py, graspologic/models/sbm_estimators.py
=> Fixed typos in models/er.py & models/sbm_estimators.py

graspologic/simulations/simulations.py
Something in an upstream dependence broke mypy - I didn't even look to see what; if this fixes it, I'm happy
=> Fixed mypy issue in MMSBM simulation

docs/reference/reference/models.rst, docs/tutorials/models/edge_swaps.ipynb, graspologic/models/edge_swaps.py, tests/test_models.py
Fixes an issue with seeding happening incorrectly and reproducibility tests
Also creates a copy of output returns
=> [BUG] Fixes reproducibility in EdgeSwapper and adds to docs

docs/conf.py, graspologic/plot/plot.py
Fixes an issue with docs building on many current open PRs 
A default option changed in intersphinx which broke one of our matplotlib references
I also ran black on this file accidentally but I figured that we might as well have it match formatting for the rest of the codebase
=> Fixed intersphinx bug and formatted docs/conf.py

graspologic/utils/utils.py
Fixed #938
this changed the documentation in to_laplacians from including the sqrt of the nodes from in the description of D to including the sqrt in the equations after the fact.
this did not fix the part of #938 that asks, "why do i/o for some and not others?"
=> Corrected notation in documentation of to_laplacians 

docs/reference/release.rst
=> Added release notes for 2.0.0

docs/tutorials/embedding/CovariateAssistedEmbed.ipynb
=> Fixed bug in seaborn usage in CASE tutorial

docs/tutorials/embedding/CovariateAssistedEmbed.ipynb
=> Actual release of 2.0.0

setup.cfg
=> Incremented bugfix version

setup.cfg
=> Updated dependencies to include typing-extensions

CONTRIBUTING.md, README.md, docs/reference/release.rst, docs/tutorials/embedding/CovariateAssistedEmbed.ipynb, graspologic/match/solver.py, setup.cfg, tests/test_match.py
=> Release 2.0.1

CONTRIBUTING.md
Corrected python 3.8 to python 3.
=> Minor typo in contributing guidelines

docs/reference/release.rst
=> Updated release notes for 3.0.0

.github/workflows/build.yml, README.md, graspologic/models/edge_swaps.py, setup.cfg
=> Added Python 3.11

pyproject.toml
=> use pep440 style versions

.github/workflows/publish.yml, pyproject.toml
=> add fetch-depth, fetch-tags options
